### PR TITLE
Major refactor and convert to ES6

### PR DESCRIPTION
**Pull request by mbilker**
Just a list of the major changes I made:
- Moved the files so N1 could find them
- Conversion to ES6
- Explicit binding of methods to `this`

The popover should be closed by `<Gif>` and not directly use a DOM method to focus on it.

### CODE REVIEW

**Comment by noahbuscher** [comment]
@mbilker Thanks a ton! :raised_hands:

**Comment by mbilker** [comment]
You are welcome!

**Comment by mbilker** [comment]
Here is me testing it.

 

> On Dec 18 2015, at 7:56 pm, Noah Buscher &lt;notifications@github.com&gt;
wrote:  

>

> [@mbilker](https://github.com/mbilker) Thanks a ton! :raised_hands:

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/noahbus
cher/N1-Jiffy/pull/4#issuecomment-165929197).

**Comment by mbilker** [comment]
Awe, it doesn't render properly.

**Comment by noahbuscher** [comment]
@mbilker Lol - meta... Wonder why :octocat: doesn't render it properly... Perhaps we need to wrap the `img` elems in a `div` instead of `span`?

**Comment by mbilker** [comment]
It detected them fine, its that there is no space in between them.

**Comment by mbilker** [comment]
See.



  

> On Dec 18 2015, at 8:04 pm, Noah Buscher &lt;notifications@github.com&gt;
wrote:  

>

> [@mbilker](https://github.com/mbilker) Lol - meta... Wonder why
:octocat:
doesn't render it properly... Perhaps we need to wrap the `img` elems in a
`div` instead of `span`?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/noahbus
cher/N1-Jiffy/pull/4#issuecomment-165929765).

**Comment by mbilker** [comment]
Never mind then

**Comment by noahbuscher** [comment]
:see_no_evil: It's okay - maybe just a weird GitHub thing.

**Pull request merged**
